### ISSUE TITLE
i18n - Toscano

### ISSUE THREAD

**Issue by LorenzoScebba** [LorenzoScebba/emojiperanto#20]

**Comment by LorenzoScebba** [comment]
Taken by @McMatthew

**Comment by McMatthew** [comment]
👀=A darò n'ucchiada
✔️=Ho f'ní
💩=Sta cosa la fa schifu
🥦➕🏃➡️🐌=N cioccu l'é plu sveltu
👨‍🔧❄️=Ste tranquìì, che provava solamentu
🤷‍♂️=Ansò cumalè
🙏🆘=Oh Dio pensug tè
🐛😡=A ghe stà un guai, cazzo
🔇️=Zittii e arpiattà
💸🔧=Basta che tmà pagu e tla ranghiu
🤣🍑📤=Murir da u ridr
🗡=Puttost mazzemu
🙏🥳☠️🙎💩=A sarei cuntent la accuppassii quel pezzu da merda
🔢🥩=L'è success tutt in semlu
🚫🐛✨=Un l'è nù sbagliu, l'é fatt apposta
🌬️❔=A buon pro, creidu?
✂️👐=A tal taj cal mann
🤦=Ch'a figüra da balurdi
💁👜😇❤️=Al signúr l'è sempre cun me

**Comment by LorenzoScebba** [comment]
"💁👜😇❤️=Al signúr l'è sempre cun me" --> Le emoji sono appropriate o vanno cambiate?

👨‍🔧❄️=Ste tranquìì, che provava solamentu --> Le emoji sono decisamente non appropriate, in italiano usiamo 👨‍🔧🦥 per dire di stare calmi, magari al posto di "stavo solo facendo dei test" possiamo dire anche in toscano di star tranquilli?
